[config]
skip_core_tasks = true

[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
    "server",
    "web",
]
TARGET_DIR="target/debug"

[env.production]
TARGET_DIR="target/release"

[tasks.default]
workspace = false
dependencies = ["update"]

# Update
[tasks.update]
workspace = false
dependencies = ["make_bin", "update_bin_members"]

[tasks.make_bin]
command = "cargo"
args = ["run", "--manifest-path", "build_tools/Cargo.toml", "--bin", "mkdir", "bin"]

[tasks.update_bin_members]
run_task = { name = "update_bin", fork = true }
