[env]
RELEASE_FLAG = "--dev"

[env.production]
RELEASE_FLAG = ""

# Clean
[tasks.clean]
command = "cargo"
args = ["clean"]

# Update
[tasks.update_bin]
command = "cargo"
args = ["run", "--manifest-path", "../build_tools/Cargo.toml", "--bin", "cp", "pkg", "../bin/static/pkg"]
dependencies = ["build", "update_static"]

[tasks.update_static]
command = "cargo"
args = ["run", "--manifest-path", "../build_tools/Cargo.toml", "--bin", "cp", "static", "../bin/static"]

# Build
[tasks.build]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "@@remove-empty(RELEASE_FLAG)"]

# Lint
[tasks.clippy]
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--all-features", "--", "--deny", "warnings", "--deny", "clippy::pedantic", "--deny", "clippy::nursery", "--deny", "clippy::use_self"]

[tasks.fmt]
install_crate = { rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "-V" }
command = "cargo"
args = ["fmt"]
